<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common-tests.props" />

  <PropertyGroup>
    <!-- Target frameworks -->
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT' And $(ContinuousIntegrationBuild) == 'true' ">
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PPWCode.Vernacular.NHibernate.IV.Tests.csproj.DotSettings"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IV.Test\PPWCode.Vernacular.NHibernate.IV.Test.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="hibernate.cfg.xml"/>
    <Content Include="hibernate.cfg.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="log4net.config"/>
    <Content Include="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="appsettings.json"/>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
