<Project Sdk="Microsoft.NET.Sdk">
    <!-- ... -->

    <ItemGroup>
        <!-- nuget package dependencies -->
        <PackageReference Include="PPWCode.Vernacular.NHibernate.III" Version="4.0.0" />
        <PackageReference Include="PPWCode.Vernacular.NHibernate.III.SqlServer" Version="4.0.0" />
        <PackageReference Include="PPWCode.Vernacular.NHibernate.III.CastleWindsor" Version="4.0.0" />
    </ItemGroup>

    <!-- ... -->
</Project>
