<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props"/>

    <!-- nuget package -->
    <PropertyGroup>
        <Description>The PPWCode Vernacular NHibernate DI library version IV.</Description>
        <PackageTags>ppwcode vernacular nhibernate orm</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\IV\PPWCode.Vernacular.NHibernate.IV.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

</Project>
