<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.props" />
  
  <!-- nuget package -->
  <PropertyGroup>
    <Description>The PPWCode Vernacular NHibernate Castle Windsor library version III.</Description>
    <PackageTags>ppwcode vernacular nhibernate orm castle windsor</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="Castle.Windsor" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\III\PPWCode.Vernacular.NHibernate.III.csproj"/>
  </ItemGroup>

</Project>
